### ISSUE TITLE
not working in Intellij Idea

### ISSUE THREAD

**Issue by yingqiaoott** [MichalHecko/SSLPoke#1]
This is a very nice tool. 

I run the SSLPoke in the IDE, the SSLHandshakeException with handshake_failure always happens. No logs appears with environment variable javax.net.debug=all. In the case that I run its jar file in command line of a terminal, it works fine. I can see the logs as well. 

Any suggestion?

**Comment by yingqiaoott** [comment]
I figure out how to do it. Thanks!

**Comment by MichalHecko** [comment]
Is possible for you to describe where the problem was ? Thanks.
